name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
inputs:
  bucket:
    description: 'The s3 bucket name'
    required: true
  bucket-region:
    description: 'The region of the s3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files'
    required: true
  outputs:
    website-url:
      description: 'The URL of deployed website'
runs:
  using: 'node16'   # node run - java script run time
  main: 'main.js'   # pre and post for extra stuff

